data:
  image_size: 64
  channels: 3
  train_data_dir: './demo_data/train/'
  test_data_dir: './demo_data/test/'
  num_workers: 1
  conditional: true
  tensorboard: './logs'

model:
  in_channels: 3
  out_ch: 3
  ch: 128
  ch_mult: [1, 2, 2, 2]
  num_res_blocks: 2
  attn_resolutions: [16]
  dropout: 0.0
  resamp_with_conv: true

diffusion:
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  num_diffusion_timesteps: 1000

training:
  batch_size: 4
  n_epochs: 10
  resume: './checkpoints'  
  seed: 42

sampling:
  batch_size: 4
  sampling_timesteps: 25

optim:
  optimizer: "Adam"
  lr: 1e-4
